base:
    seed: &seed 42
model:
    type: Llama
    path: model
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 128
    bs: 1
    seq_len: 512
    preproc: general
    seed: *seed
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: [wikitext2, c4, ptb]
    download: False
    path: path
    bs: 1
    seq_len: 2048
quant:
    method: OsPlus
    weight:
        bit: 8
        symmetric: False
        granularity: per_channel
    act:
        bit: 8
        symmetric: False
        granularity: per_token
    special:
        use_shift: True
    quant_out: True
save:
    save_fp: False
    save_quant: False
    save_path: ./save